import type { Metadata } from "next";

import { SanityLive } from "@/sanity/lib/live";
import "./globals.css";

import Header from "@/app/components/layout/Header";
import Main from "@/app/components/layout/Main";
import React from "react";

import { chaneyExtended, chaneyUltraExtended, hostGrotesk, geistMono, } from "@/app/fonts/fonts"

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${chaneyExtended.variable} ${chaneyUltraExtended.variable} ${hostGrotesk.variable} ${geistMono.variable} antialiased`}>

        <Header />

        <Main>
            {children}
        </Main>

        <SanityLive />

        </body>
        </html>
    )
}